<?php
/**
 * PH2M_Gdpr
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Gdpr
 * @copyright  Copyright (c) 2018 PH2M SARL
 * @author     PH2M SARL <contact@ph2m.com> : http://www.ph2m.com/
 *
 */

?>
<div class="page-title">
    <h1><?php echo $this->__('Download my account data') ?></h1>
</div>

<div>
    <form action="<?php echo Mage::helper('phgdpr')->getDownloadAccountDataUrl() ?>" method="POST">
        <button type="submit" class="button">
            <span>
                <?php echo $this->__('Download my account data') ?>
            </span>
        </button>
    </form>
</div>

<?php if($file = $this->getCustomerDataFile()): ?>
    <a href="<?php echo Mage::helper('phgdpr')->getDownloadContentFileUrl() ?>" target="_blank"><?php echo $this->__('Download my account data') ?></a>
<?php endif; ?>
