<?php
/**
 * PH2M_GDPR
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   GDPR
 * @copyright  Copyright (c) 2018 PH2M SARL
 * @author     PH2M SARL <contact@ph2m.com> : http://www.ph2m.com/
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @var $this Mage_GoogleAnalytics_Block_Ga
 */


?>
<?php
$_helper = $this->helper('googleanalytics');
$_accountId = $_helper->getAccountId();
?>
<?php if (!$this->helper('core/cookie')->isUserNotAllowSaveCookie()): ?>
    <?php if($_helper->isUseUniversalAnalytics()): ?>
        <script type="text/javascript">
            tarteaucitron.user.analyticsUa = '<?php echo $_accountId ?>';
            tarteaucitron.user.analyticsMore = function () {
                <?php echo $this->_getPageTrackingCode($_accountId) ?>
                <?php echo $this->_getOrdersTrackingCode() ?>
            };
            (tarteaucitron.job = tarteaucitron.job || []).push('analytics');
        </script>
    <?php else: ?>
        <script type="text/javascript">
            tarteaucitron.user.gajsUa = '<?php echo $_accountId ?>';
            tarteaucitron.user.gajsMore = function () {
                <?php echo $this->_getPageTrackingCode($_accountId) ?>
                <?php echo $this->_getOrdersTrackingCode() ?>
            };
            (tarteaucitron.job = tarteaucitron.job || []).push('gajs');
        </script>
    <?php endif; ?>
<?php endif; ?>
